### ISSUE TITLE
Refactor test

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/react-apollo#25]
Right now the tests are overly verbose in their boilerplate, and they don't accurately test common lifecycle events that can happen with changing props.

### Todo:

- [ ] split the connect test into files for `prop api`, `redux integration`, `queries`, and `mutations`
- [ ] create reusable boilerplate
- [ ] better test lifecycle events

Hopefully this will clean up some issues like https://github.com/apollostack/react-apollo/issues/20

**Comment by jbaxleyiii** [comment]
Incrementally better with #50
